<a href="https://colab.research.google.com/github/RamaBharti/Classification-of-Handwritten-Digit-on-MNSIT-dataset/blob/master/MNSIT_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import urllib.request
import gzip
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import randint
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

url = 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz'
filename, headers = urllib.request.urlretrieve(url, 'train-images-idx3-ubyte.gz')
# Load training images
with gzip.open(filename, 'rb') as f:
    data = np.frombuffer(f.read(), np.uint8, offset=16)
    X_train = data.reshape(-1, 28*28)

url = 'http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz'
filename, headers = urllib.request.urlretrieve(url, 'train-labels-idx1-ubyte.gz')
# Load training labels
with gzip.open(filename, 'rb') as f:
    data = np.frombuffer(f.read(), np.uint8, offset=8)
    y_train = data

url = 'http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz'
filename, headers = urllib.request.urlretrieve(url, 't10k-images-idx3-ubyte.gz')
# Load test images
with gzip.open(filename, 'rb') as f:
    data = np.frombuffer(f.read(), np.uint8, offset=16)
    X_test = data.reshape(-1, 28*28)

url = 'http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz'
filename, headers = urllib.request.urlretrieve(url, 't10k-labels-idx1-ubyte.gz')
# Load test labels
with gzip.open(filename, 'rb') as f:
    data = np.frombuffer(f.read(), np.uint8, offset=8)
    y_test = data

# Create an ANN classifier
ann_clf = MLPClassifier()
ann_clf.fit(X_train, y_train)
y_pred = ann_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy_ann_clf: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

# Define the hyperparameters for grid search
param_grid = {
    'hidden_layer_sizes': [(100,), (100, 50), (50,)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01]
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(ann_clf, param_grid, cv=3, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print the best hyperparameters and score
print('Best Hyperparameters: ', grid_search.best_params_)
print('Best Score: ', grid_search.best_score_)
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate the evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy_grid: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))


# Create an ANN classifier with best hyperparameters
ann_clf = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', alpha=0.0001)

# Evaluate the ANN classifier using k-fold cross-validation
scores = cross_val_score(ann_clf, X_train, y_train, cv=5, n_jobs=-1)
# Print the cross-validation scores
print('Cross-Validation Scores: ', scores)
ann_clf.fit(X_train,y_train)

# Make predictions on the test set
y_pred = ann_clf.predict(X_test)

# Calculate the evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of best: ', accuracy)
print("Precision:", precision_score(y_test, y_pred, average='macro'))
print("Recall:", recall_score(y_test, y_pred, average='macro'))
print("F1-score:", f1_score(y_test, y_pred, average='macro'))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy_ann_clf:  0.9636
Precision: 0.9635604591554824
Recall: 0.9630680279030799
F1-score: 0.9632282239292579
Confusion matrix:
 [[ 961    2    3    0    1    1    6    0    4    2]
 [   1 1118    1    3    1    1    1    0    9    0]
 [   9    7  981   10    5    0    2    8   10    0]
 [   1    1    4  982    0    4    0    6    9    3]
 [   2    2    2    0  952    0    7    5    2   10]
 [   2    1    1   30    1  836    4    5    7    5]
 [   8    4    3    0    3   11  923    0    6    0]
 [   0    5    8    3    5    0    0 1000    1    6]
 [   4    0    3    7    7    6    3    4  929   11]
 [   3    3    1    9   19    6    0   10    4  954]]


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Best Hyperparameters:  {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (100, 50), 'solver': 'adam'}
Best Score:  0.9652499999999998
Accuracy_grid:  0.9702
Precision: 0.9701512609043055
Recall: 0.9696797833028631
F1-score: 0.9698452441644084
Confusion matrix:
 [[ 963    0    3    0    2    2    5    2    1    2]
 [   0 1122    5    0    1    2    1    2    2    0]
 [   6    0  995   10    4    0    2    9    5    1]
 [   0    0    2  983    0    4    0    7    4   10]
 [   2    1    0    0  949    0    5    4    5   16]
 [   2    1    2   20    3  842    9    0    8    5]
 [   4    3    1    0    4    2  939    0    5    0]
 [   1    2    4    6    1    0    0 1004    1    9]
 [   5    1    1   13    7    9    2    2  927    7]
 [   2    3    0    6    7    2    1    8    2  978]]
Cross-Validation Scores:  [0.96583333 0.97033333 0.96783333 0.96266667 0.96733333]
Accuracy of best:  0.9713
Precision: 0.9712566039259345
Recall: 0.9710934127760351
F1-score: 0.9711221989217449
